address: 0.0.0.0:10081
transport: tcp
protocol:
  type: ws
  targets:
    - matching_path: /some-path-you-like
      protocol:
        type: vmess
        cipher: any
        user_id: some-random-uuid
rules:
  - mask: 0.0.0.0/0
    action: allow
    client_proxy: direct
